name = "multipost-seo-worker"
main = "app.js"
compatibility_date = "2024-04-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "multi-post-db"
database_id = "19dfae46-a6cb-4e88-ab7c-2ab2fea3279a"

[vars]
# DO NOT put your secret keys here. 
# Just leave these as placeholders or the actual Public Client IDs.
GOOGLE_CLIENT_ID = "YOUR_GOOGLE_ID"
TIKTOK_CLIENT_KEY = "YOUR_TIKTOK_KEY"
FB_CLIENT_ID = "YOUR_FB_ID"
